"""Statistical analysis module for E0 benchmark evaluation.

Pure stdlib, deliberately — no scipy/numpy. A seeded bootstrap is fully reproducible across
Python versions and needs no pinned third-party numerics; the RHI outer-loop doctrine
(`docs/04-workflows-and-loops/rhi-outer-loop.md`) requires exactly that kind of replayable number.

Every result mirrors the `GateReport` doctrine: **absence of a verdict must never be
representable as a pass.** `p_value=0.05` and `beats_noise_floor = delta > 0` were H5 — the
statistics equivalent of H1's hardcoded gates — and are gone. A comparison that cannot be
honestly computed (too few runs, an empty or unpaired suite) returns `None`, never a default.
"""

from __future__ import annotations

import math
import random

from sagiha.domain.benchmark import BenchmarkRun, ComparisonResult, NoiseFloor

#: Default bootstrap parameters. Fixed so `bench --aa` output is reproducible run over run —
#: the whole point of seeding is that nobody has to trust "it looked stable when I ran it".
DEFAULT_ALPHA = 0.05
DEFAULT_BOOTSTRAP_ITERATIONS = 2000
DEFAULT_SEED = 0


def _task_outcomes(run: BenchmarkRun) -> dict[str, list[bool]]:
    """Map `task_id -> [resolved, ...]`, preserving every repetition in encounter order.

    `BenchmarkRunner.run_suite(k=...)` appends `k` results per task into one flat
    `BenchmarkRun.results` tuple. A `task_id -> bool` dict (last-write-wins) would silently
    collapse those `k` repetitions to one, disagreeing with `compute_pass_rate` (which
    correctly averages all of them) the moment `k > 1` — exactly the `--runs 3` invocation the
    v2-S4 exit gate specifies. Keeping the list lets `paired_deltas` pair repetition-by-repetition.
    """
    outcomes: dict[str, list[bool]] = {}
    for r in run.results:
        outcomes.setdefault(r.task_id, []).append(r.resolved)
    return outcomes


def paired_deltas(control: BenchmarkRun, treatment: BenchmarkRun) -> list[float]:
    """Per-repetition pass/fail deltas (`+1`/`0`/`-1`) over the task_ids common to both runs.

    Joins on `task_id` rather than positionally — an unpaired comparison (different task sets,
    or results out of order) measures something other than the harness, and silently zipping
    two result lists would manufacture a paired comparison that never happened. Within a
    task_id, repetition `i` of `control` pairs with repetition `i` of `treatment` (both runs are
    generated by the same `run_suite(k=...)` walk, so repetition order is comparable); any
    repetition-count mismatch for a task pairs only up to the shorter of the two.
    """
    control_by_task = _task_outcomes(control)
    treatment_by_task = _task_outcomes(treatment)
    common = sorted(set(control_by_task) & set(treatment_by_task))
    deltas: list[float] = []
    for t in common:
        control_reps = control_by_task[t]
        treatment_reps = treatment_by_task[t]
        for c_val, t_val in zip(control_reps, treatment_reps, strict=False):
            deltas.append(float(t_val) - float(c_val))
    return deltas


def mcnemar_exact(b: int, c: int) -> float:
    """Exact two-sided McNemar test over discordant pairs.

    `b`, `c` are the two discordant counts (control-pass/treatment-fail and control-fail/
    treatment-pass respectively — order does not matter, the test is symmetric). This is the
    correct test for paired binary pass/fail outcomes; a Wilcoxon signed-rank test (as an
    earlier draft of this sprint proposed) assumes an ordinal/continuous statistic and is the
    wrong tool for a pass/fail pair.

    Returns `1.0` when there is nothing discordant to test (b == c == 0) — perfect agreement is
    not evidence of a difference, and the caller must not read that as "significant".
    """
    n = b + c
    if n == 0:
        return 1.0
    k = min(b, c)
    # Two-sided exact binomial p-value under H0: P(X<=k) + P(X>=n-k) for X ~ Binomial(n, 0.5),
    # computed exactly via math.comb rather than a normal approximation.
    total = sum(math.comb(n, i) for i in range(0, k + 1))
    total += sum(math.comb(n, i) for i in range(n - k, n + 1))
    # The two tails overlap exactly when k == n - k (a perfectly symmetric split); correct for
    # the double-counted middle term instead of over-reporting significance.
    if n - k <= k:
        total -= math.comb(n, k)
    p = total / (2**n)
    return min(1.0, max(0.0, p))


def bootstrap_ci(
    deltas: list[float],
    *,
    alpha: float = DEFAULT_ALPHA,
    iterations: int = DEFAULT_BOOTSTRAP_ITERATIONS,
    seed: int = DEFAULT_SEED,
) -> tuple[float, float]:
    """Percentile bootstrap confidence interval over paired per-task deltas.

    `random.Random(seed)` rather than the module-global RNG: the same `deltas`/`seed` always
    produce the same interval, which is what makes a CI-committed noise floor auditable rather
    than merely plausible-looking.
    """
    if not deltas:
        return (0.0, 0.0)
    rng = random.Random(seed)
    n = len(deltas)
    means: list[float] = []
    for _ in range(iterations):
        sample = [deltas[rng.randrange(n)] for _ in range(n)]
        means.append(sum(sample) / n)
    means.sort()
    lo_idx = int((alpha / 2) * iterations)
    hi_idx = int((1 - alpha / 2) * iterations) - 1
    hi_idx = min(hi_idx, iterations - 1)
    return (means[lo_idx], means[hi_idx])


def holm(pvalues: list[float]) -> list[float]:
    """Holm–Bonferroni step-down correction, order-preserving.

    Returns adjusted p-values in the same order as the input. Screening many candidates against
    one uncorrected threshold manufactures winners from noise — this is the plan's required
    multiple-comparison correction (`docs/04-workflows-and-loops/rhi-outer-loop.md` Tier 3).
    """
    m = len(pvalues)
    if m == 0:
        return []
    indexed = sorted(range(m), key=lambda i: pvalues[i])
    adjusted = [0.0] * m
    running_max = 0.0
    for rank, idx in enumerate(indexed):
        value = min(1.0, (m - rank) * pvalues[idx])
        running_max = max(running_max, value)
        adjusted[idx] = running_max
    return adjusted


class StatisticalAnalyzer:
    """Analyzes benchmark runs for pass rate and statistical significance."""

    @staticmethod
    def compute_pass_rate(run: BenchmarkRun) -> float:
        if not run.results:
            return 0.0
        resolved_count = sum(1 for r in run.results if r.resolved)
        return resolved_count / len(run.results)

    @staticmethod
    def compute_noise_floor(
        run_a: BenchmarkRun,
        run_b: BenchmarkRun,
        *,
        alpha: float = DEFAULT_ALPHA,
        iterations: int = DEFAULT_BOOTSTRAP_ITERATIONS,
        seed: int = DEFAULT_SEED,
    ) -> NoiseFloor:
        """A/A noise floor: two runs of the *unmodified* harness, same suite.

        `mean_delta` is the observed A/A drift; `confidence_interval` bounds it via a seeded
        bootstrap rather than the previous `(0.0, mean_delta * 1.5)` placeholder arithmetic.
        """
        deltas = paired_deltas(run_a, run_b)
        mean_delta = abs(sum(deltas) / len(deltas)) if deltas else 0.0
        ci = bootstrap_ci(deltas, alpha=alpha, iterations=iterations, seed=seed)
        return NoiseFloor(
            manifest_id=run_a.suite_id,
            runs_per_task=2,
            mean_delta=mean_delta,
            confidence_interval=ci,
            alpha=alpha,
            k_runs=2,
            n_tasks=len(deltas),
            seed=seed,
        )

    @staticmethod
    def compare_runs(
        control: BenchmarkRun,
        treatment: BenchmarkRun,
        *,
        noise_floor: NoiseFloor | None = None,
    ) -> ComparisonResult:
        """Paired comparison, judged against `noise_floor` when one is supplied.

        Without a noise floor, `beats_noise_floor` stays `None` — there is nothing honest to
        compare against, and reporting `True` (the pre-H5-fix default) would be exactly the
        fabrication this rewrite exists to remove.
        """
        deltas = paired_deltas(control, treatment)
        n = len(deltas)
        rate_control = StatisticalAnalyzer.compute_pass_rate(control)
        rate_treatment = StatisticalAnalyzer.compute_pass_rate(treatment)
        delta_pass_rate = rate_treatment - rate_control

        b = sum(1 for d in deltas if d < 0)  # control-pass, treatment-fail
        c = sum(1 for d in deltas if d > 0)  # control-fail, treatment-pass
        n_discordant = b + c

        if n < 2 or n_discordant == 0:
            return ComparisonResult(
                control_agent_id=control.agent_id,
                treatment_agent_id=treatment.agent_id,
                delta_pass_rate=delta_pass_rate,
                p_value=None,
                adjusted_p_value=None,
                n_discordant=n_discordant,
                method="mcnemar_exact",
                beats_noise_floor=None,
            )

        p_value = mcnemar_exact(b, c)
        beats_floor: bool | None = None
        # `noise_floor.n_tasks == 0` means the floor itself was never honestly computed (no
        # pairable A/A tasks) — its `mean_delta`/`confidence_interval` are both the `0.0`
        # placeholder default, which every positive delta would trivially "beat". Treating that
        # as a real floor is H5's fabrication reappearing one level up; `None` is the honest
        # answer when there is nothing to judge against.
        if noise_floor is not None and noise_floor.n_tasks > 0:
            beats_floor = (
                delta_pass_rate > noise_floor.mean_delta
                and delta_pass_rate > noise_floor.confidence_interval[1]
            )

        return ComparisonResult(
            control_agent_id=control.agent_id,
            treatment_agent_id=treatment.agent_id,
            delta_pass_rate=delta_pass_rate,
            p_value=p_value,
            adjusted_p_value=None,
            n_discordant=n_discordant,
            method="mcnemar_exact",
            beats_noise_floor=beats_floor,
        )
