#!/usr/bin/env bash
# scripts/verify.sh — the single sanctioned instrument for the docs/STATUS.md
# regression table.
#
# Runs every project gate, captures each real exit code, and emits a markdown
# table on stdout in exactly the shape STATUS expects. Numbers in STATUS are
# copied from a saved run of this script and are never typed from memory
# (defect C-2).
#
# Deliberately NOT `set -e`: every gate must run and every failure must be
# reported, not just the first one.
set -uo pipefail

cd "$(dirname "$0")/.."

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

FAILED=0

# name|status|detail  — accumulated rows for the final table
ROWS=()

# run <slug> <label> -- <command...>
#   Executes the command, tees its output to $WORK/<slug>.log, records the exit
#   code in $WORK/<slug>.rc. Never aborts the script.
run() {
    local slug="$1" label="$2"
    shift 3 # slug, label, "--"
    printf '\n=== %s ===\n' "$label"
    "$@" >"$WORK/$slug.log" 2>&1
    local rc=$?
    echo "$rc" >"$WORK/$slug.rc"
    cat "$WORK/$slug.log"
    printf -- '--- %s: exit %d ---\n' "$label" "$rc"
    if [ "$rc" -ne 0 ]; then FAILED=1; fi
    return 0
}

mark() { # mark <rc> -> ✅ / ❌
    if [ "$1" -eq 0 ]; then echo "✅"; else echo "❌"; fi
}

rc_of() { cat "$WORK/$1.rc" 2>/dev/null || echo 1; }

# ---------------------------------------------------------------- host facts
GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")"
GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")"
PY_VERSION="$(python3 --version 2>&1)"
if command -v podman >/dev/null 2>&1; then
    PODMAN_VERSION="$(podman --version 2>&1)"
    PODMAN_PRESENT="present"
else
    PODMAN_VERSION="podman: absent"
    PODMAN_PRESENT="absent"
fi

printf '=== host facts ===\n'
printf 'git      : %s (%s)\n' "$GIT_SHA" "$GIT_BRANCH"
printf 'python   : %s\n' "$PY_VERSION"
printf 'podman   : %s\n' "$PODMAN_VERSION"
printf 'date     : %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --------------------------------------------------------------------- gates
run pytest      "pytest (full)"          -- uv run pytest -q
run pytest_np   "pytest (not podman)"    -- uv run pytest -q -m "not podman"
run pyright     "pyright"                -- uv run pyright src/sagiha
run imports     "lint-imports"           -- uv run lint-imports
run ruff        "ruff check"             -- uv run ruff check .
run format      "ruff format --check"    -- uv run ruff format --check .
run budget      "docs budget"            -- python3 scripts/docs_budget.py --max 15000
run links       "link integrity"         -- python3 scripts/check_links.py
run catalog     "event catalog"          -- python3 scripts/gen_event_catalog.py --check

# ------------------------------------------------------------- derived facts
PORT_COUNT="$(grep -rn "(Protocol)" src/sagiha/ports/ | wc -l | tr -d ' ')"
PORT_FILES="$(grep -rln "(Protocol)" src/sagiha/ports/ | wc -l | tr -d ' ')"

# pytest counts: "N passed" / "N failed"
count_passed() { grep -oE '[0-9]+ passed' "$WORK/$1.log" | tail -1 | grep -oE '[0-9]+' || echo "?"; }
count_failed() { grep -oE '[0-9]+ failed' "$WORK/$1.log" | tail -1 | grep -oE '[0-9]+' || echo "0"; }

PYTEST_PASSED="$(count_passed pytest)"
PYTEST_FAILED="$(count_failed pytest)"
PYTEST_NP_PASSED="$(count_passed pytest_np)"

# pyright: "N errors"
PYRIGHT_ERRORS="$(grep -oE '[0-9]+ error' "$WORK/pyright.log" | tail -1 | grep -oE '[0-9]+' || echo "?")"

# ruff: "Found N errors" (or "All checks passed")
if grep -q "All checks passed" "$WORK/ruff.log"; then
    RUFF_ERRORS=0
else
    RUFF_ERRORS="$(grep -oE 'Found [0-9]+ error' "$WORK/ruff.log" | tail -1 | grep -oE '[0-9]+' || echo "?")"
fi

# ruff format --check: "N files would be reformatted"
if grep -qE 'would be reformatted' "$WORK/format.log"; then
    FORMAT_FILES="$(grep -oE '[0-9]+ files? would be reformatted' "$WORK/format.log" | tail -1 | grep -oE '[0-9]+' || echo "?")"
else
    FORMAT_FILES=0
fi

# docs budget: "normative word count N"
BUDGET_WORDS="$(grep -oE 'word count [0-9,]+' "$WORK/budget.log" | tail -1 | grep -oE '[0-9,]+' || echo "?")"

# links: "N dead relative link(s)"
if [ "$(rc_of links)" -eq 0 ]; then
    DEAD_LINKS=0
else
    DEAD_LINKS="$(grep -oE '[0-9]+ dead relative link' "$WORK/links.log" | tail -1 | grep -oE '[0-9]+' || echo "?")"
fi

# lint-imports: "Contracts: N kept, M broken."
IMPORTS_KEPT="$(grep -oE '[0-9]+ kept' "$WORK/imports.log" | tail -1 | grep -oE '[0-9]+' || echo "?")"
IMPORTS_TOTAL="$(grep -cE '^[A-Za-z].*(KEPT|BROKEN)' "$WORK/imports.log" || echo "5")"

# ---------------------------------------------------------------- the table
cat <<EOF

================================================================================
# Frozen Regression Signals

Generated by \`scripts/verify.sh\` at \`$GIT_SHA\` ($GIT_BRANCH) on $(date -u +%Y-%m-%d).
Host: $PY_VERSION · $PODMAN_VERSION

| Signal | Result | Status | Command |
| :--- | :--- | :--- | :--- |
| Tests (full) | ${PYTEST_PASSED} passed, ${PYTEST_FAILED} failed | $(mark "$(rc_of pytest)") | \`uv run pytest -q\` |
| Tests (not podman) | ${PYTEST_NP_PASSED} passed | $(mark "$(rc_of pytest_np)") | \`uv run pytest -q -m "not podman"\` |
| Type check | ${PYRIGHT_ERRORS} errors | $(mark "$(rc_of pyright)") | \`uv run pyright src/sagiha\` |
| Import contracts | ${IMPORTS_KEPT}/${IMPORTS_TOTAL} kept | $(mark "$(rc_of imports)") | \`uv run lint-imports\` |
| Lint | ${RUFF_ERRORS} errors | $(mark "$(rc_of ruff)") | \`uv run ruff check .\` |
| Format | ${FORMAT_FILES} files would reformat | $(mark "$(rc_of format)") | \`uv run ruff format --check .\` |
| Docs budget | ${BUDGET_WORDS} normative words (ceiling 15,000) | $(mark "$(rc_of budget)") | \`python3 scripts/docs_budget.py --max 15000\` |
| Link integrity | ${DEAD_LINKS} dead relative links | $(mark "$(rc_of links)") | \`python3 scripts/check_links.py\` |
| Event catalog | $([ "$(rc_of catalog)" -eq 0 ] && echo "in sync" || echo "out of sync") | $(mark "$(rc_of catalog)") | \`python3 scripts/gen_event_catalog.py --check\` |

**Ports:** ${PORT_COUNT} Protocols across ${PORT_FILES} files (\`grep -rn "(Protocol)" src/sagiha/ports/\`).
**Podman on this host:** ${PODMAN_PRESENT}.
================================================================================
EOF

if [ "$FAILED" -ne 0 ]; then
    printf '\nVERIFY: FAILED — one or more gates are red.\n'
    exit 1
fi
printf '\nVERIFY: OK — all gates green.\n'
exit 0
